Fix for watchlist footer

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -90,25 +90,37 @@ jobs:
       - name: Deploy to EC2
         run: |
           ssh -o StrictHostKeyChecking=no ec2-user@34.233.52.146 << 'EOF'
-          set -e
-          cd ~/environment/microservices
-          docker-compose -f Admin/project/admin-docker-compose.yaml -p admin down || true
-          docker-compose -f User/project/user-docker-compose.yaml -p user down || true
-          docker network rm app-network || true
-          docker network create app-network || true
-          cd Admin/project
-          docker-compose -f admin-docker-compose.yaml -p admin up --build --force-recreate -d
-          cd ../../User/project
-          docker-compose -f user-docker-compose.yaml -p user up --build --force-recreate -d
-          cd ../../nginx
-          docker-compose -f docker-compose.yml -p nginx up --build --force-recreate -d
-          docker network inspect app-network
-          docker ps
+            set -e
+            cd ~/environment/microservices
+            docker-compose -f Admin/project/admin-docker-compose.yaml -p admin down || true
+            docker-compose -f User/project/user-docker-compose.yaml -p user down || true
+            docker network rm app-network || true
+            docker network create app-network || true
+            cd Admin/project
+            docker-compose -f admin-docker-compose.yaml -p admin up --build --force-recreate -d
+            cd ../../User/project
+            docker-compose -f user-docker-compose.yaml -p user up --build --force-recreate -d
+            cd ../../nginx
+            docker-compose -f docker-compose.yml -p nginx up --build --force-recreate -d
+            docker network inspect app-network
+            docker ps
+          EOF
+
+      - name: Rollback to Previous Version if Deployment Fails
+        if: failure()  # Triggered only if the previous step fails
+        run: |
+          echo "Deployment failed, rolling back to previous version."
+          ssh -o StrictHostKeyChecking=no ec2-user@34.233.52.146 << 'EOF'
+            cd ~/environment/microservices
+            git checkout HEAD~1  # Revert to previous commit (rollback)
+            docker-compose -f Admin/project/admin-docker-compose.yaml -p admin up --build --force-recreate -d
+            docker-compose -f User/project/user-docker-compose.yaml -p user up --build --force-recreate -d
+            docker-compose -f nginx/docker-compose.yml -p nginx up --build --force-recreate -d
           EOF
 
       - name: Verify Deployment
         run: |
-          ssh -o StrictHostKeyChecking=no ec2-user@34.233.52.146 << 'EOF'
-          docker ps
-          docker network inspect app-network
+          ssh -o StrictHostKeyChecking=no ec2-user@3224.233.52.146 << 'EOF'
+            docker ps
+            docker network inspect app-network
           EOF
